### ISSUE TITLE
Android 12

### ISSUE THREAD

**Issue by faisalhusain007** [weberbox/PiFire-Android#3]
The app seems to keep crashing in Android 12. Sorry dont have anymore details.
![pifire crash](https://user-images.githubusercontent.com/36872476/154393831-00964ff9-3735-469e-b2fd-32c866c637b1.jpeg)

**Comment by weberbox** [comment]
I did see your crash reports. It is not due to Android 12. From my guesses you are running either an old version of PiFire (prior to 1.2.2) or possibly the current development branch. 

The crash issue should be resolved in the next version of the app but if you are running a version of PiFire that is older than 1.2.2 (the current main branch) or you are using the current development branch (1.2.7-dev3) then the app will not load any data as the app is not supported before 1.2.2 and some of the API's have changed in 1.2.7-dev3. 

Do you know what PiFire version you are using?

**Comment by faisalhusain007** [comment]
Yes I am running 1.2.7 dev version, I will try version 1.3.3 of the android app, sorry I assumed it was android 12, I just had it pushed to my phone a few days ago and some apps behave the same way.

Thanks for the quick response.

**Comment by faisalhusain007** [comment]
Confirm everything works as expected with 1.4.0 android app on server 1.2.7 dev.

Thank you

**Comment by weberbox** [comment]
Awesome. Thanks for pointing out the issue on older versions at least I could push a version to prevent it from crashing.

**Comment by weberbox** [comment]
@faisalhusain007 I see you found some other bug in the dev version and had a crash. It is strange as it is not crashing on my devices or emulators. 

I am looking into the crash to see why it may have happened but is there anything you could tell me about it? 

Is it still happening when launching the app?

**Comment by faisalhusain007** [comment]
No its because I have added some code for the DC fan on my server, the issue is that the settings.json has 2 extra outputs dcfan and psu, but when i pull the update from git my common and grillplat get overwritten but the settings.json still have reference to the output pins. This causes both the server side and android app to crash. 

Sorry about that will fix and test.

**Comment by weberbox** [comment]
No worries at all. I am not sure this crash was due to settings.json as I believe the app should just ignore any extra settings that may be in the json. If it was malformed json it could cause an issue but even then the app should catch the exception and just not update the settings locally. Anyway thanks for responding back!

**Comment by faisalhusain007** [comment]
I believe the issue might be that control exits with an error but only after trying to initialize either monitor or startup, when it runs through the function GetOutpStatus in grillplat

**Comment by weberbox** [comment]
The crashing issue should not have been related to your setup. I found an issue in the app and corrected it in version 1.4.0-dev3 or later. That should solve the random crash.

**Comment by faisalhusain007** [comment]
Great thanks for the update. I was wondering if you have a compiled version of 1.4.0-dev3 with the android OneSignal, would like to test it.

**Comment by weberbox** [comment]
Ya there is v1.4.0-dev3 and I just uploaded v1.4.0-dev4 a couple days ago. You can find them on the releases page [here](https://github.com/weberbox/PiFire-Android/releases)

**Comment by faisalhusain007** [comment]
Thanks a lot will test it out soon.
